//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.29 at 10:27:26 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bulldog.ru/eshop/ws/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.bulldog.eshop.ws.products;
