CREATE TABLE IF NOT EXISTS "ROLES" (
    "RAW_ID" INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "ROLE_NAME" VARCHAR(50) NOT NULL,
    CONSTRAINT UNIQUE_ROLE_NAME UNIQUE("ROLE_NAME"));
INSERT INTO "ROLES" (ROLE_NAME) VALUES('ROLE_SUPERADMIN');
INSERT INTO "ROLES" (ROLE_NAME) VALUES('ROLE_ADMIN');
INSERT INTO "ROLES" (ROLE_NAME) VALUES('ROLE_MANAGER');
INSERT INTO "ROLES" (ROLE_NAME) VALUES('ROLE_CUSTOMER');

CREATE TABLE IF NOT EXISTS "ROLE_PERMISSIONS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "ROLE_ID" INT NOT NULL,
    "PERMISSION_ID" INT NOT NULL,
    CONSTRAINT UNIQUE_ROLE_PERMISSION UNIQUE("ROLE_ID", "PERMISSION_ID"));
INSERT INTO "ROLE_PERMISSIONS" (ROLE_ID, PERMISSION_ID) VALUES(1, 1);
INSERT INTO "ROLE_PERMISSIONS" (ROLE_ID, PERMISSION_ID) VALUES(2, 2);
INSERT INTO "ROLE_PERMISSIONS" (ROLE_ID, PERMISSION_ID) VALUES(3, 3);
INSERT INTO "ROLE_PERMISSIONS" (ROLE_ID, PERMISSION_ID) VALUES(3, 4);

CREATE TABLE IF NOT EXISTS "USERS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "SESSION_ID" UUID DEFAULT RANDOM_UUID(),
    "USERNAME" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "FIRSTNAME" VARCHAR(255),
    "LASTNAME" VARCHAR(255),
    "LOCKED" BOOLEAN DEFAULT FALSE,
    "ENABLED" BOOLEAN DEFAULT TRUE,
    "EXPIRED" TIMESTAMP DEFAULT PARSEDATETIME('31-12-9999', 'dd-MM-yyyy'),
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UNIQUE_USERNAME UNIQUE("USERNAME"),
    CONSTRAINT UNIQUE_SESSION UNIQUE("SESSION_ID"));
INSERT INTO "USERS" (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES('root', '$2a$10$w.HKE6NUwLDiHDNNkUcIxu3d06Bp.J84P2/TsosF.19iSezyu1WXq', 'root', 'root');
INSERT INTO "USERS" (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES('admin', '$2a$10$w.HKE6NUwLDiHDNNkUcIxu3d06Bp.J84P2/TsosF.19iSezyu1WXq', 'John', 'Smith');
INSERT INTO "USERS" (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES('marleyb@pisem.net', '$2a$10$w.HKE6NUwLDiHDNNkUcIxu3d06Bp.J84P2/TsosF.19iSezyu1WXq', 'Bob', 'Marley');
INSERT INTO "USERS" (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES('bulldog@pisem.net', '$2a$10$w.HKE6NUwLDiHDNNkUcIxu3d06Bp.J84P2/TsosF.19iSezyu1WXq', 'Aleksey', 'Seregin');

CREATE TABLE IF NOT EXISTS "USER_ROLES" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" INT NOT NULL,
    CONSTRAINT UNIQUE_USER_ROLE UNIQUE("USER_ID", "ROLE_ID"));
INSERT INTO "USER_ROLES" (USER_ID, ROLE_ID) VALUES(1, 1);
INSERT INTO "USER_ROLES" (USER_ID, ROLE_ID) VALUES(2, 2);
INSERT INTO "USER_ROLES" (USER_ID, ROLE_ID) VALUES(3, 3);
INSERT INTO "USER_ROLES" (USER_ID, ROLE_ID) VALUES(4, 4);

CREATE TABLE IF NOT EXISTS "CATEGORIES" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UNIQUE_TITLE UNIQUE("TITLE"));
INSERT INTO "CATEGORIES" (TITLE) VALUES('Other');
INSERT INTO "CATEGORIES" (TITLE) VALUES('Painting');
INSERT INTO "CATEGORIES" (TITLE) VALUES('Writing');

CREATE TABLE IF NOT EXISTS "PRODUCTS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "PRICE" DECIMAL DEFAULT 0.0,
    "CATEGORY" BIGINT DEFAULT 1,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CATEGORY_ID FOREIGN KEY ("CATEGORY") REFERENCES CATEGORIES("RAW_ID"));
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Blue Pen', 5.45, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Red Pen', 5.45, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Green Pen', 5.45, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Pencils Box', 20.0, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paper Block', 10.25, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 3.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 3.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 2.95, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 2.85, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 4.0, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scratchpad', 2.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scratchpad', 2.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scratchpad', 2.2, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scotch tape', 1.25, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scotch tape', 1.75, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scotch tape', 2.25, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scotch tape', 4.5, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 3.0, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 3.55, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 4.5, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 5.25, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 6.15, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Set of pens', 12.45, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Set of pens', 13.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Set of pens', 13.5, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Set of pens', 13.8, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Ruler', 1.45, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Ruler', 1.5, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Ruler', 2.0, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Ruler', 2.45, 1);

CREATE TABLE IF NOT EXISTS "ORDERS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "SESSION" UUID NOT NULL,
    "SUM" DECIMAL DEFAULT 0.0,
    "ADDRESS" VARCHAR(255) NOT NULL,
    "PHONE" VARCHAR(50) NOT NULL,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ORDER_ITEMS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "ORDER_ID" BIGINT NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "COUNT" INT DEFAULT 1,
    "PRICE" DECIMAL DEFAULT 0.0,
    "SUM" DECIMAL DEFAULT 0.0,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDER_ID FOREIGN KEY ("ORDER_ID") REFERENCES ORDERS("RAW_ID"));

CREATE TABLE IF NOT EXISTS "PERMISSIONS" (
    "RAW_ID" INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "PERMISSION_NAME" VARCHAR(50) NOT NULL,
    CONSTRAINT UNIQUE_PERMISSION_NAME UNIQUE("PERMISSION_NAME"));
INSERT INTO "PERMISSIONS" (PERMISSION_NAME) VALUES('ALL');
INSERT INTO "PERMISSIONS" (PERMISSION_NAME) VALUES('MANAGE_USERS');
INSERT INTO "PERMISSIONS" (PERMISSION_NAME) VALUES('MANAGE_PRODUCTS');
INSERT INTO "PERMISSIONS" (PERMISSION_NAME) VALUES('MANAGE_ORDERS');

CREATE TABLE IF NOT EXISTS "PICTURES" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "SOURCE" VARCHAR NOT NULL,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UNIQUE_PICTURE_SOURCE UNIQUE("SOURCE"));
INSERT INTO "PICTURES" (SOURCE) VALUES('https://bookshop.binrush.com/wp-content/uploads/2019/08/bic-pen.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://bookshop.binrush.com/wp-content/uploads/2019/11/bic-red.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://bookshop.binrush.com/wp-content/uploads/2019/11/bic-green.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://www.rexlondon.com/sites/dotcom.pleasetest.co.uk/files/6-pencils-periodic-table-box-26861_3.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://www.brightideascrafts.co.uk/wp-content/uploads/2015/08/BI2351_big_n.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/81ar06Kx+cL._AC_SX466_.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/71+E63cYH9S._AC_SL1500_.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://i5.walmartimages.com/asr/dd17a6d5-ee3e-414d-9457-8321a1f1999c.f35bfc62d5de8a7d5607fcbc988db9a8.jpeg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://shop.googlemerchandisestore.com/store/20160512512/assets/items/largeimages/GGOEGOLC014299.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://assets.hermes.com/is/image/hermesproduct/ulysse-plain-notebook-refill-medium-model--325177A%2000-front-3-300-0-600-600_b.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/61Rh8Fh3DkL._AC_SL1042_.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://image.made-in-china.com/44f3j00CNYtUMGwgDog/Three-Dimensional-Sticky-Notes-Office-Combination-Kraft-Paper-Coil-Pad.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://image.made-in-china.com/202f0j00GmiaQKkMqtrU/Rainbow-Drawing-Scratch-Pad-Art-Book-Magic-Painting-Children-Notebook.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://s3.amazonaws.com/zcom-media/sites/a0iE000000LhWtrIAF/media/catalog/product/s/c/scotch-tape.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://cdnimg.webstaurantstore.com/images/products/large/321123/1267039.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/71wONIp693L._AC_SL1500_.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://cdn.officestationery.co.uk/products/152791-349420-500/scotch-508-clear-tape-19mmx66m-clear-ref-7000080794-pack-8-.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/81EQKf4ByJL._AC_SL1500_.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://www.bakerross.co.uk/media/catalog/product/cache/789e0244c80348f78faf6f424fee0e0f/p/o/poster-paint-pots-aw251j.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/71dyVdlH-rL._AC_SY355_.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://www.pegasusart.co.uk/img/product/02scola-artmix-poster-paints-600ml-6-colours-9031593-600.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://s7.orientaltrading.com/is/image/OrientalTrading/FXBanner_808/16-oz--washable-classic-colors-tempera-paint-10-pc-~13807557.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://static.winc.com.au/pi/58/68c5d20c77d4cae1ba0355f652c1649de72533-1040820/lgsq.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://d15bv9e9f3al6i.cloudfront.net/imgs/products/cp/950_constW/ZB67463~Zebra-Doodlerz-Gel-Pen-Set-of-10-Assorted_P1.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://www.bigbasket.com/media/uploads/p/l/40200599_1-luxor-back-to-school-pens-set-combo.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://penstore.com/bilder/artiklar/liten/105314_S.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://www.partsight.org.uk/media/catalog/product/cache/89c16c65bc351d3d228bbdf5eeba3cf3/l/a/large-print-ruler-1.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/71Yz+YiQG3L._AC_SL1500_.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/51QzEF5bi-L._AC_SL1100_.jpg');
INSERT INTO "PICTURES" (SOURCE) VALUES('https://m.media-amazon.com/images/I/61MtLqQ0SWL._AC_SY450_.jpg');

CREATE TABLE IF NOT EXISTS "PRODUCTS_PICTURES" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL,
    "PICTURE_ID" BIGINT NOT NULL,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY ("PRODUCT_ID") REFERENCES PRODUCTS("RAW_ID"),
    CONSTRAINT FK_PICTURE_ID FOREIGN KEY ("PICTURE_ID") REFERENCES PICTURES("RAW_ID"));
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (1, 1);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (2, 2);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (3, 3);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (4, 4);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (5, 5);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (6, 6);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (7, 7);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (8, 8);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (9, 9);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (10, 10);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (11, 11);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (12, 12);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (13, 13);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (14, 14);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (15, 15);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (16, 16);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (17, 17);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (18, 18);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (19, 19);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (20, 20);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (21, 21);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (22, 22);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (23, 22);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (24, 24);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (25, 25);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (26, 26);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (27, 27);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (28, 28);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (29, 29);
INSERT INTO "PRODUCTS_PICTURES" (PRODUCT_ID, PICTURE_ID) VALUES (30, 30);
