CREATE TABLE IF NOT EXISTS "ROLES" (
    "RAW_ID" INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "ROLE_NAME" VARCHAR(50) NOT NULL,
    CONSTRAINT UNIQUE_ROLE_NAME UNIQUE("ROLE_NAME"));
INSERT INTO "ROLES" (ROLE_NAME) VALUES('ROLE_SUPERADMIN');
INSERT INTO "ROLES" (ROLE_NAME) VALUES('ROLE_ADMIN');
INSERT INTO "ROLES" (ROLE_NAME) VALUES('ROLE_MANAGER');
INSERT INTO "ROLES" (ROLE_NAME) VALUES('ROLE_CUSTOMER');

CREATE TABLE IF NOT EXISTS "ROLE_PERMISSIONS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "ROLE_ID" INT NOT NULL,
    "PERMISSION_ID" INT NOT NULL,
    CONSTRAINT UNIQUE_ROLE_PERMISSION UNIQUE("ROLE_ID", "PERMISSION_ID"));
INSERT INTO "ROLE_PERMISSIONS" (ROLE_ID, PERMISSION_ID) VALUES(1, 1);
INSERT INTO "ROLE_PERMISSIONS" (ROLE_ID, PERMISSION_ID) VALUES(2, 2);
INSERT INTO "ROLE_PERMISSIONS" (ROLE_ID, PERMISSION_ID) VALUES(3, 3);
INSERT INTO "ROLE_PERMISSIONS" (ROLE_ID, PERMISSION_ID) VALUES(3, 4);

CREATE TABLE IF NOT EXISTS "USERS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "SESSION_ID" UUID DEFAULT RANDOM_UUID(),
    "USERNAME" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "FIRSTNAME" VARCHAR(255),
    "LASTNAME" VARCHAR(255),
    "LOCKED" BOOLEAN DEFAULT FALSE,
    "ENABLED" BOOLEAN DEFAULT TRUE,
    "EXPIRED" TIMESTAMP DEFAULT PARSEDATETIME('31-12-9999', 'dd-MM-yyyy'),
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UNIQUE_USERNAME UNIQUE("USERNAME"),
    CONSTRAINT UNIQUE_SESSION UNIQUE("SESSION_ID"));
INSERT INTO "USERS" (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES('root', '$2a$10$w.HKE6NUwLDiHDNNkUcIxu3d06Bp.J84P2/TsosF.19iSezyu1WXq', 'root', 'root');
INSERT INTO "USERS" (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES('admin', '$2a$10$w.HKE6NUwLDiHDNNkUcIxu3d06Bp.J84P2/TsosF.19iSezyu1WXq', 'John', 'Smith');
INSERT INTO "USERS" (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES('marleyb@pisem.net', '$2a$10$w.HKE6NUwLDiHDNNkUcIxu3d06Bp.J84P2/TsosF.19iSezyu1WXq', 'Bob', 'Marley');
INSERT INTO "USERS" (USERNAME, PASSWORD, FIRSTNAME, LASTNAME) VALUES('bulldog@pisem.net', '$2a$10$w.HKE6NUwLDiHDNNkUcIxu3d06Bp.J84P2/TsosF.19iSezyu1WXq', 'Aleksey', 'Seregin');

CREATE TABLE IF NOT EXISTS "USER_ROLES" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" INT NOT NULL,
    CONSTRAINT UNIQUE_USER_ROLE UNIQUE("USER_ID", "ROLE_ID"));
INSERT INTO "USER_ROLES" (USER_ID, ROLE_ID) VALUES(1, 1);
INSERT INTO "USER_ROLES" (USER_ID, ROLE_ID) VALUES(2, 2);
INSERT INTO "USER_ROLES" (USER_ID, ROLE_ID) VALUES(3, 3);
INSERT INTO "USER_ROLES" (USER_ID, ROLE_ID) VALUES(4, 4);

CREATE TABLE IF NOT EXISTS "CATEGORIES" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UNIQUE_TITLE UNIQUE("TITLE"));
INSERT INTO "CATEGORIES" (TITLE) VALUES('Other');
INSERT INTO "CATEGORIES" (TITLE) VALUES('Painting');
INSERT INTO "CATEGORIES" (TITLE) VALUES('Writing');

CREATE TABLE IF NOT EXISTS "PRODUCTS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "PRICE" DECIMAL DEFAULT 0.0,
    "CATEGORY" BIGINT DEFAULT 1,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CATEGORY_ID FOREIGN KEY ("CATEGORY") REFERENCES CATEGORIES("RAW_ID"));
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Blue Pen', 5.45, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Red Pen', 5.45, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Green Pen', 5.45, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Pencils Box', 20.0, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paper Block', 10.25, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 3.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 3.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 2.95, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 2.85, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Notebook', 4.0, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scratchpad', 2.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scratchpad', 2.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scratchpad', 2.2, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scotch tape', 1.25, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scotch tape', 1.75, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scotch tape', 2.25, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Scotch tape', 4.5, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 3.0, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 3.55, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 4.5, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 5.25, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Paints', 6.15, 2);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Set of pens', 12.45, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Set of pens', 13.15, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Set of pens', 13.5, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Set of pens', 13.8, 3);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Ruler', 1.45, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Ruler', 1.5, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Ruler', 2.0, 1);
INSERT INTO "PRODUCTS" (TITLE, PRICE, CATEGORY) VALUES('Ruler', 2.45, 1);

CREATE TABLE IF NOT EXISTS "ORDERS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "SESSION" UUID NOT NULL,
    "SUM" DECIMAL DEFAULT 0.0,
    "ADDRESS" VARCHAR(255) NOT NULL,
    "PHONE" VARCHAR(50) NOT NULL,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "ORDER_ITEMS" (
    "RAW_ID" BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "ORDER_ID" BIGINT NOT NULL,
    "TITLE" VARCHAR(50) NOT NULL,
    "COUNT" INT DEFAULT 1,
    "PRICE" DECIMAL DEFAULT 0.0,
    "SUM" DECIMAL DEFAULT 0.0,
    "CREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDER_ID FOREIGN KEY ("ORDER_ID") REFERENCES ORDERS("RAW_ID"));

CREATE TABLE IF NOT EXISTS "PERMISSIONS" (
    "RAW_ID" INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    "PERMISSION_NAME" VARCHAR(50) NOT NULL,
    CONSTRAINT UNIQUE_PERMISSION_NAME UNIQUE("PERMISSION_NAME"));
INSERT INTO "PERMISSIONS" (PERMISSION_NAME) VALUES('ALL');
INSERT INTO "PERMISSIONS" (PERMISSION_NAME) VALUES('MANAGE_USERS');
INSERT INTO "PERMISSIONS" (PERMISSION_NAME) VALUES('MANAGE_PRODUCTS');
INSERT INTO "PERMISSIONS" (PERMISSION_NAME) VALUES('MANAGE_ORDERS');
