server:
  port: 8082
spring:
  application:
    name: service-soap
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:8091/eureka}
    fetchRegistry: true